### ISSUE TITLE
Add searx.dojocasts.com

### ISSUE THREAD

**Issue by sigfriedseldeslachts** [dalf/searx-instances#12]
[searx.dojocasts.com](https://searx.dojocasts.com) and [www.searx.dojocasts.com](https://www.searx.dojocasts.com)

At this moment no custom modifications.

- IPv6 supported (custom address only for the searx instance)
- [BuyPass](https://buypass.com) Certificate
- TLS1.2 & TLS1.3 only
- HSTS
- Behind nginx proxy
- No logging whatsoever
- Image proxying
- A+ on SSL Labs
- Hosted by Hetzner in Germany

Any issues or suggestions may be sent to me.

Edit for clarification: the nameservers use CloudFlare but none of the traffic is proxied through CloudFlare. It is just DNS. **No proxy through CF**

**Comment by unixfox** [comment]
It's better if you remove the deprecated ciphers like stated on this website: https://cryptcheck.fr/https/searx.dojocasts.com :smiley:

**Comment by sigfriedseldeslachts** [comment]
Hi,

Thanks for responding. I think the cipher set is already fix but that it is cached, the IPv6 address still shows the previous one. This test doesn't show them anymore: https://cryptcheck.fr/tls/searx.dojocasts.com:443
Also most of the time I use SSL Labs, this tool does not show TLSv1.3.

Nice to see that you discovered something new today :smile:!
Note on BuyPass it does not support ACMEv2, so no wildcard certificates.
