### ISSUE TITLE
Add https://searx-anon.duckdns.org/

### ISSUE THREAD

**Issue by superoraculus** [dalf/searx-instances#14]

**Comment by dalf** [comment]
If you have control over the nginx configuration (if this is the front server you are using):
* https://ssl-config.mozilla.org/#server=nginx&version=1.17.0&config=intermediate&openssl=1.1.1d ( to improve the score from https://cryptcheck.fr/https/searx-anon.duckdns.org )
* https://github.com/searx/searx-docker/blob/ecf10d41db11a7e3e5b50fe82e6020ada5dacab3/Caddyfile#L19-L45 ( to improve the score from https://observatory.mozilla.org/ )

Nothing mandatory

**Comment by superoraculus** [comment]
I've checked my webserver config and made the suggested changes.

Still, my instance has a good score on Qualys SSL, but not on Mozilla Observatory.

For example, HTTP Strict Transport Security (HSTS) is recognized on Qualys, but not Observatory...

GOOD:
https://www.ssllabs.com/ssltest/analyze.html?d=searx-anon.duckdns.org

BAD:
https://observatory.mozilla.org/

**Comment by unixfox** [comment]
You have to click on "reinitiate the scan" button, I did it for you: https://observatory.mozilla.org/analyze/searx-anon.duckdns.org

**Comment by superoraculus** [comment]
Oops... Thx!

A+ now :)

**Comment by dalf** [comment]
Ahh, I forgot one thing: since https://github.com/dalf/searx-stats2/issues/4 , the ASN with privacy issues are displayed with a red background.

searx-anon.duckdns.org is hosted by Google Cloud, which is in the list:
https://github.com/dalf/searx-stats2/blob/d11a618470eec1d311953371a7f242e07af807a5/searxstats/data/asn.py#L156

Actually, I don't know if it should be the case or not.

**Comment by superoraculus** [comment]
Fair enough! Google is definitely a problem.

But wouldn't the lack of privacy fall on me, the instance owner?

**Comment by superoraculus** [comment]
Whatever the rule, I accept.

**Comment by dalf** [comment]
From the documentation:
> Users are neither tracked nor profiled. Additionally, searx can be used over Tor for online anonymity.

The users may not choose your instance to keep theirs privacies. If I say it differently, it would be better if you could install your instance in another server.

Anyhow, https://searx.space will highlight the ASN, so anyone can choose your instance according to her/his need.

**Comment by unixfox** [comment]
I would say it's up to you to host it anywhere you want, and we won't deny your instance if it's hosted in a privacy invasive hosting provider.
Thanks to searx.space the user is warned before entering on your instance that it's hosted at Google and will decide himself if whenever he wants to use your instance or not.

**Comment by superoraculus** [comment]
@unixfox Correct.

**Comment by return42** [comment]
Dump question from my side .. as long as all the outside communication is ssl, is there any privacy loss / drainage?  The searx process itself is in memory, nothing is written onto the filesystem of the hoster and all localhost (127.0.0.1) communication should also be in memory .. or did I missed something?

**Comment by dalf** [comment]
May wrong guess.

If:
* A data center and a search engine belong to the same organization
* The data center and the search engine log the inbound and outbound TCP connections (without deciphering the stream).
* The search engine log the requests.

Then, technically, the organization can find the matches between the two logs, and in the end find which requests belong to which user IP.

This is a lot of "if", I don't know what is done really.

**Comment by unixfox** [comment]
Or worst case scenario the host is already compromised and there is a sniffer that log plain text HTTP requests from searx to the reverse proxy.

**Comment by return42** [comment]
@dalf @unixfox : thanks for your feedback ..

> This is a lot of "if", I don't know what is done really.

yes :) .. as long as POST is used, there are much simpler ways to get this informations.

> Or worst case scenario the host is already compromised  and there is a sniffer that log the plain text HTTP requests from searx to the reverse proxy.

If the host is compromised, the aggressor can do everything, but this is nothing a hoster would ever do.  I asked the question in context of saying "google is a risky" hoster and is flaged red at https://searx.space/

With your  answers I came to the conclusion: The only thing they can collect are IPs but for this they  already have 8.8.8.8 DNS which is much more verbose privacy drain ;)

**Comment by unixfox** [comment]
> If the host is compromised, the aggressor can do everything, but this is nothing a hoster would ever do. I asked the question in context of saying "google is a risky" hoster and is flaged red at searx.space

It can also be done unintentionally, every big cloud provider has a daemon installed by default which serves as a purpose of telemetry and/or gather information for the user panel (like displaying graphs): [microsoft azure](https://github.com/Azure/WALinuxAgent), [google cloud](https://cloud.google.com/logging/docs/agent), [digitalocean](https://github.com/digitalocean/do-agent), [oracle cloud](https://docs.oracle.com/cd/E11081_01/doc/doc.21/e10898/ovmagent.htm). This agent could malfunction and log every plain text HTTP requests like cloudflare already did with its cloudbleed: https://en.wikipedia.org/wiki/Cloudbleed and be discovered only years after the bug.

**Comment by return42** [comment]
> This agent could malfunction and log every plain text HTTP requests 

could he sniff the loopback device (127.0.0.1)? .. as far I know loopback device is in the kernel, as long as the kernel isn't patched or debuged, are there any chance to sniff?

> We can not know/trust everything of what's installed by default in the various OS templates of big cloud providers.

That's the point .. I think. But in general it means you can't trust in any hoster nor in his quality.
