### ISSUE TITLE
Add https://www.finden.ga

### ISSUE THREAD

**Issue by miicha** [dalf/searx-instances#17]
This instance contains a small change regarding the layout and is capable to search in the user defined language and additionally in english.
Source code is available at: https://github.com/miicha/searx/tree/finden_tk

**Comment by dalf** [comment]
I can't acces https://www.finden.ga

**Comment by dalf** [comment]
The server seems slow even for the css and  the js.
Is the server hosted behind your personnal ADSL connection ?
If it is the case, I don't advice to it to searx.space: it will kill your upload.

Do note that you can ignore this, just confirm the addition to searx.space.

**Comment by miicha** [comment]
Unfortunately it is currently routed through an ADSL connection, and additionally there seem to be some DNS problems as well, so might be better to close the request and don't add it until I found a better solution...
