### ISSUE TITLE
https://suche.uferwerk.org

### ISSUE THREAD

**Issue by vasyugan** [dalf/searx-instances#18]
https://suche.uferwerk.org

So far no specific customization

**Comment by dalf** [comment]
A few things, nothing mandatory:
* on the search result page, there are 404 HTTP errors on path like suche.uferwerk.org/morty/?mortyurl=anURL&mortyhash=aHash
  * either your reverse proxy doesn't send requests to morty
  * either you don't install morty. In this case comment out: https://github.com/asciimoo/searx/blob/b7105da2af11c4f5cd34d2cba61da5a0f3f36d95/searx/settings.yml#L32-L34
* https://cryptcheck.fr/https/suche.uferwerk.org : 
  * RSA and DH are considered weak.
  * TLS1.0 and TLS1.1 too.
* According to https://observatory.mozilla.org/ there are few missing HTTP headers:
  * Content Security Policy, X-Content-Type-Options, X-Frame-Options, X-XSS-Protection
  * see https://github.com/searx/searx-docker/blob/master/Caddyfile#L23-L32 for the values.

**Comment by vasyugan** [comment]
> A few things, nothing mandatory:
> 
>     * on the search result page, there are 404 HTTP errors on path like suche.uferwerk.org/morty/?mortyurl=anURL&mortyhash=aHash
>       
>       * either your reverse proxy doesn't send requests to morty
>       * either you don't install morty. In this case comment out: https://github.com/asciimoo/searx/blob/b7105da2af11c4f5cd34d2cba61da5a0f3f36d95/searx/settings.yml#L32-L34

I use[ your docker-compose file](https://github.com/searx/searx-docker/blob/master/docker-compose.yaml), however I had to comment a few things out.

1.  because our server runs NGINX, through which services are reverse proxied, ports 80 and 443 are taken and I have no use for caddy.
2. There is another node.js application running, therefore port 3000 is in use, therefore I had to comment out the ports stanza of the "morty" service. I don't know how to make searx interact with morty instance on a different port
3. I am not sure if filtron is of any use if caddy is not used.  The only service that seems to refer to filtron in the docker-compose.yml is caddy.
4. Is your recommendation that we should disable RSA in the NGINX config?
5. I'll have a look at the headers later today, whn I have time. 


 

> 
>     * https://cryptcheck.fr/https/suche.uferwerk.org :
>       
>       * RSA and DH are considered weak.
>       * TLS1.0 and TLS1.1 too.
> 
>     * According to https://observatory.mozilla.org/ there are few missing HTTP headers:
>       
>       * Content Security Policy, X-Content-Type-Options, X-Frame-Options, X-XSS-Protection
>       * see https://github.com/searx/searx-docker/blob/master/Caddyfile#L23-L32 for the values.

**Comment by dalf** [comment]
### Morty

Disclamer: untested.

In the docker-compose.yml file:
 * https://github.com/searx/searx-docker/blob/e4e3aa48f448c79873897fa216dd78cda9a43011/docker-compose.yaml#L72-L89
 * replace line 78 with ```127.0.0.1:anotherPort:3000``` (anotherPort = whatever free port above 1024)

In nginx configuration:
```nginx
location /morty/ {
    proxy_pass http://127.0.0.1:anotherPort;
}
```

### Filtron

In nginx configuraition:
```nginx
location / {
    proxy_pass http://127.0.0.1:4040;
}
```

4040 value come from here: https://github.com/searx/searx-docker/blob/e4e3aa48f448c79873897fa216dd78cda9a43011/docker-compose.yaml#L36

### HTTPS configuration
See https://ssl-config.mozilla.org/#server=nginx&version=1.17.0&config=modern&openssl=1.1.1d&guideline=5.4
  * Change the openssl / nginx version 


### searx.conf
So you nginx configuration _may_ look like this:
```nginx
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    return 301 https://$host$request_uri;
}

server {
    # copy / paste from ssl-config.mozilla.org
    # 
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    ssl_certificate /path/to/signed_cert_plus_intermediates;
    ssl_certificate_key /path/to/private_key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # modern configuration
    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers off;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /path/to/root_CA_cert_plus_intermediates;

    # replace with the IP address of your resolver
    resolver 127.0.0.1;

    # filtron
    location / {
       proxy_pass http://127.0.0.1:4040;
    }
 
    # morty
    location /morty/ {
        proxy_pass http://127.0.0.1:anotherPort;
    }
}
```

**Comment by vasyugan** [comment]
@dalf Applied all your suggestions.
Seems to work!
Thanks!

**Comment by vasyugan** [comment]
@dalf Hm, after applying the suggested config, the server always returns "rate limit exceeded" when searching for something... Here is the log. It doesn't reveal, which component causes the failure:

```
2020/03/10 07:50:44 [error] 12173#12173: *270814 connect() failed (111: Connection refused) while connecting to upstream, client: 2003:d3:c716:bf00:d12d:c0a9:88fe:365, server: suche.uferwerk.org, request: "POST / HTTP/2.0", upstream: "http://[::1]:4040/", host: "suche.uferwerk.org"
2020/03/10 07:50:44 [warn] 12173#12173: *270814 upstream server temporarily disabled while connecting to upstream, client: 2003:d3:c716:bf00:d12d:c0a9:88fe:365, server: suche.uferwerk.org, request: "POST / HTTP/2.0", upstream: "http://[::1]:4040/", host: "suche.uferwerk.org"
2020/03/10 07:50:59 [error] 12173#12173: *270814 connect() failed (111: Connection refused) while connecting to upstream, client: 2003:d3:c716:bf00:d12d:c0a9:88fe:365, server: suche.uferwerk.org, request: "GET /static/themes/oscar/css/logicodev.min.css HTTP/2.0", upstream: "http://[::1]:4040/static/themes/oscar/css/logicodev.min.css", host: "suche.uferwerk.org"
2020/03/10 07:50:59 [warn] 12173#12173: *270814 upstream server temporarily disabled while connecting to upstream, client: 2003:d3:c716:bf00:d12d:c0a9:88fe:365, server: suche.uferwerk.org, request: "GET /static/themes/oscar/css/logicodev.min.css HTTP/2.0", upstream: "http://[::1]:4040/static/themes/oscar/css/logicodev.min.css", host: "suche.uferwerk.org"

```

**Comment by vasyugan** [comment]
> @dalf Hm, after applying the suggested config, the server always returns "rate limit exceeded" when searching for something... Here is the log. It doesn't reveal, which component causes the failure:
> 
> ```
> 2020/03/10 07:50:44 [error] 12173#12173: *270814 connect() failed (111: Connection refused) while connecting to upstream, client: 2003:d3:c716:bf00:d12d:c0a9:88fe:365, server: suche.uferwerk.org, request: "POST / HTTP/2.0", upstream: "http://[::1]:4040/", host: "suche.uferwerk.org"
> 2020/03/10 07:50:44 [warn] 12173#12173: *270814 upstream server temporarily disabled while connecting to upstream, client: 2003:d3:c716:bf00:d12d:c0a9:88fe:365, server: suche.uferwerk.org, request: "POST / HTTP/2.0", upstream: "http://[::1]:4040/", host: "suche.uferwerk.org"
> 2020/03/10 07:50:59 [error] 12173#12173: *270814 connect() failed (111: Connection refused) while connecting to upstream, client: 2003:d3:c716:bf00:d12d:c0a9:88fe:365, server: suche.uferwerk.org, request: "GET /static/themes/oscar/css/logicodev.min.css HTTP/2.0", upstream: "http://[::1]:4040/static/themes/oscar/css/logicodev.min.css", host: "suche.uferwerk.org"
> 2020/03/10 07:50:59 [warn] 12173#12173: *270814 upstream server temporarily disabled while connecting to upstream, client: 2003:d3:c716:bf00:d12d:c0a9:88fe:365, server: suche.uferwerk.org, request: "GET /static/themes/oscar/css/logicodev.min.css HTTP/2.0", upstream: "http://[::1]:4040/static/themes/oscar/css/logicodev.min.css", host: "suche.uferwerk.org"
> ```

Obviously an issue with filtron, because when I let nginx proxy searx directly, everything is fine.

**Comment by dalf** [comment]
What is the output of ```docker logs filtron``` ?

Make sure that ./searx/uwsgi.ini contains:
```
add-header = Connection: close
``` 
( see https://github.com/asciimoo/searx/blob/master/dockerfiles/uwsgi.ini#L35-L37 )

**Comment by vasyugan** [comment]
> What is the output of `docker logs filtron` ?

Nothing revealing:

```
$ docker container logs -f filtron
2020/03/10 06:55:56 13 rules loaded from /etc/filtron/rules.json
2020/03/10 06:55:56 API listens on 10.10.10.3:4041
2020/03/10 06:55:56 Proxy listens on 10.10.10.3:4040
2020/03/10 07:09:47 13 rules loaded from /etc/filtron/rules.json
2020/03/10 07:09:47 API listens on 10.10.10.3:4041
2020/03/10 07:09:47 Proxy listens on 10.10.10.3:4040



``` 
> Make sure that ./searx/uwsgi.ini contains:
> 
> ```
> add-header = Connection: close
> ```

Was there already.


> ( see https://github.com/asciimoo/searx/blob/master/dockerfiles/uwsgi.ini#L35-L37 )

**Comment by dalf** [comment]
I forgot some conf:
```nginx
location / {
    ...
    proxy_set_header   Host             $http_host;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Scheme         $scheme;
}
``` 

same for /morty

**Comment by vasyugan** [comment]
> I forgot some conf:
> same for /morty

Duly noted and added, but this doesn't solve the "rate limit exceeded". Isn't there a way to extract more information from filtron?

**Comment by dalf** [comment]
Go with a browser to http://127.0.0.1:4041/rules if you can (see https://github.com/asciimoo/filtron/#api )

Otherwise add to the nginx configuration:

```nginx
    location /filtron {
       proxy_pass http://127.0.0.1:4041;
    }
```

Then go to suche.uferwerk.org/filtron/rules

You will see which filtron rule is triggered.

**Comment by vasyugan** [comment]
> Go with a browser to http://127.0.0.1:4041/rules if you can (see https://github.com/asciimoo/filtron/#api )
> 
> Otherwise add to the nginx configuration:
> 
> ```nginx
>     location /filtron {
>        proxy_pass http://127.0.0.1:4041;
>     }
> ```
> 
> Then go to suche.uferwerk.org/filtron/rules
> 
> You will see which filtron rule is triggered.

Hm...

All I get is

` {"error": "Not found"}`

**Comment by vasyugan** [comment]
The one thing I notice running docker-compose logs -f in the searx-docker directory is this here:

```
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.4:8080
searx            | [uWSGI] getting INI configuration from /etc/searx/uwsgi.ini
searx            | [FATAL tini (1)] Unexpected error when forwarding signal: 'Operation not permitted'
searx            | searx version 0.16.0-51-a5d3585a

```

**Comment by dalf** [comment]
Sorry for the trial and error.

Without nginx configuration :
```sh
curl http://127.0.0.1:4041/rules
```

If it doesn't work, could you add a trailing slash to http://127.0.0.1:4041 :

```nginx
location /filtron {
       proxy_pass http://127.0.0.1:4041/;
}
```

and try again suche.uferwerk.org/filtron/rules

( ref https://serverfault.com/questions/562756/how-to-remove-the-path-with-an-nginx-proxy-pass )

> [FATAL tini (1)] Unexpected error when forwarding signal: 'Operation not permitted'

It seems to be a capabilities problem.
You can try to remove (for the searx container): 
```yaml
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
```

**Comment by vasyugan** [comment]
Curl works.

Commenting out those lines you suggested doesn't change things. 

`[{"interval":0,"limit":0,"name":"stats.searx.xyz","match_count":0,"filters":["Header:X-Forwarded-For=(2a01:4f8:161:542e::2|5.9.58.49)"],"aggregations":null,"actions":[{"name":"log","params":null}],"subrules":null,"disabled":false,"stop":true},{"interval":3,"limit":25,"name":"IP limit, all paths","match_count":0,"filters":null,"aggregations":["Header:X-Forwarded-For"],"actions":[{"name":"block","params":{"message":"Rate limit exceeded, try again later."}}],"subrules":null,"disabled":false,"stop":false},{"interval":30,"limit":200,"name":"useragent limit, all paths","match_count":0,"filters":null,"aggregations":["Header:X-Forwarded-For","Header:User-Agent"],"actions":[{"name":"block","params":{"message":"Rate limit exceeded, try again later."}}],"subrules":null,"disabled":false,"stop":true},{"interval":0,"limit":0,"name":"search request","match_count":15,"filters":["Param:q","Path=^(/|/search)$"],"aggregations":null,"actions":null,"subrules":[{"interval":0,"limit":0,"name":"robot agent forbidden","match_count":0,"filters":["Header:User-Agent=([Cc][Uu][Rr][Ll]|[wW]get|Scrapy|splash|JavaFX|FeedFetcher|python-requests|Go-http-client|Java|Jakarta|okhttp|HttpClient|Jersey|Python|libwww-perl|Ruby|SynHttpClient|UniversalFeedParser)"],"aggregations":null,"actions":[{"name":"block","params":{"message":"Rate limit exceeded"}}],"subrules":null,"disabled":false,"stop":true},{"interval":0,"limit":0,"name":"bot forbidden","match_count":0,"filters":["Header:User-Agent=(Googlebot|GoogleImageProxy|bingbot|Baiduspider|yacybot|YandexMobileBot|YandexBot|Yahoo! Slurp|MJ12bot|AhrefsBot|archive.org_bot|msnbot|MJ12bot|SeznamBot|linkdexbot|Netvibes|SMTBot|zgrab|James BOT|Sogou|Abonti|Pixray|Spinn3r|SemrushBot|Exabot|ZmEu|BLEXBot|bitlybot)"],"aggregations":null,"actions":[{"name":"block","params":{"message":"Rate limit exceeded"}}],"subrules":null,"disabled":false,"stop":true},{"interval":0,"limit":0,"name":"block missing accept-language","match_count":0,"filters":["!Header:Accept-Language"],"aggregations":null,"actions":[{"name":"block","params":{"message":"Rate limit exceeded"}}],"subrules":null,"disabled":false,"stop":true},{"interval":0,"limit":0,"name":"block Connection:close","match_count":15,"filters":["Header:Connection=close"],"aggregations":null,"actions":[{"name":"block","params":{"message":"Rate limit exceeded"}}],"subrules":null,"disabled":false,"stop":true},{"interval":0,"limit":0,"name":"block no brotli support","match_count":0,"filters":["!Header:Accept-Encoding=[; ]?br[; ]?"],"aggregations":null,"actions":[{"name":"block","params":{"message":"Rate limit exceeded"}}],"subrules":null,"disabled":false,"stop":true},{"interval":0,"limit":0,"name":"block accept everything","match_count":0,"filters":["!Header:Accept=text/html"],"aggregations":null,"actions":[{"name":"block","params":{"message":"Rate limit exceeded"}}],"subrules":null,"disabled":false,"stop":true},{"interval":3600,"limit":4,"name":"rss/json limit","match_count":0,"filters":["Param:format=(csv|json|rss)"],"aggregations":["Header:X-Forwarded-For"],"actions":[{"name":"block","params":{"message":"Rate limit exceeded, try again later."}}],"subrules":null,"disabled":false,"stop":true},{"interval":3,"limit":3,"name":"IP limit","match_count":0,"filters":null,"aggregations":["Header:X-Forwarded-For"],"actions":[{"name":"block","params":{"message":"Rate limit exceeded, try again later."}}],"subrules":null,"disabled":false,"stop":false},{"interval":600,"limit":60,"name":"IP and useragent limit","match_count":0,"filters":null,"aggregations":["Header:X-Forwarded-For","Header:User-Agent"],"actions":[{"name":"block","params":{"message":"Rate limit exceeded, try again later."}}],"subrules":null,"disabled":false,"stop":true}],"disabled":false,"stop":false}]`

**Comment by dalf** [comment]
Okay this one (after copy / paste to https://beautifier.io/ ):
```json
{
    "interval": 0,
    "limit": 0,
    "name": "block Connection:close",
    "match_count": 15,
    "filters": ["Header:Connection=close"],
    "aggregations": null,
    "actions": [{
      "name": "block",
      "params": {
        "message": "Rate limit exceeded"
      }
    }],
    "subrules": null,
    "disabled": false,
    "stop": true
  }
```

So remove this block https://github.com/searx/searx-docker/blob/b4ce81ab604df1fe5bc6e5d8666e542335c665d0/rules.json#L63-L72 from rules.json, restart filtron and it should be fine.

If it still doesn't work, same curl ..., https://beautifier.io/, search for match_count.

**Comment by vasyugan** [comment]
Thanks, this works now!! Awesome!!

**Comment by vasyugan** [comment]
Another issue I found: in the system service template, the variable is called "SEARX_DOCKERCOMPOSEFILE", however in start.sh it is SEARXDOCKERCOMPOSEFILE

**Comment by dalf** [comment]
Wait a minute, the instance is already declared : 
https://github.com/dalf/searx-instances/blob/master/searxinstances/instances.yml#L181
!
:-)
