### ISSUE TITLE
Add https://www.sitecrawl.de

### ISSUE THREAD

**Issue by ITC-Media** [dalf/searx-instances#19]

**Comment by dalf** [comment]
Nothing mandatory: 
  * https://cryptcheck.fr/https/www.sitecrawl.de :
    * RSA and DH are considered weak.
    * TLS1.0 and TLS1.1 too.
  * According to https://observatory.mozilla.org/ there are few missing HTTP headers:
    * Content Security Policy, X-Content-Type-Options, X-Frame-Options, X-XSS-Protection
    * see https://github.com/searx/searx-docker/blob/master/Caddyfile#L23-L32 for the values.

If you can use https://ssl-config.mozilla.org/ and https://github.com/dalf/searx-instances/issues/18#issuecomment-596687003

**Comment by ITC-Media** [comment]
Ok, then dont put it on the Instances list. BTW: SiteCrawl runs since 2018 without problems.

**Comment by unixfox** [comment]
Why are you taking dalf's tips as an offense? You aren't required to follow his advices.

**Comment by dalf** [comment]
@ITC-Media just ignore my previous message, can you just confirm the addition to searx.space ?

**Comment by ITC-Media** [comment]
closed now
