### ISSUE TITLE
Add https://occusearch.de

### ISSUE THREAD

**Issue by openminded42** [dalf/searx-instances#21]

**Comment by dalf** [comment]
@openminded42 : searx is miss-configured 
https://occusearch.de/opensearch.xml shows ```http://127.0.0.1:4004/```

You should set baseurl to ```https://occusearch.de``` in settings.yml: https://github.com/asciimoo/searx/blob/b7105da2af11c4f5cd34d2cba61da5a0f3f36d95/searx/settings.yml#L16
