### ISSUE TITLE
Add https://search.bunker.is

### ISSUE THREAD

**Issue by DarkDev-ai** [dalf/searx-instances#25]
It would be great if you'd add https://search.bunker.is to the list of public instances.

Regards

**Comment by dalf** [comment]
One question: is it your instance ?

A few notes if this is your instance:
* the server doesn't answer on the IPv6.
* according to https://cryptcheck.fr/ , you can use https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1d&guideline=5.4 to get an up to date nginx configuration.

**Comment by DarkDev-ai** [comment]
Yes, it's my instance.

IPv6 doesn't work at  the moment and is planned to be readded in a few days.

nginx is up to date and https://cryptcheck.fr rates search.bunker.is with A+.
