### ISSUE TITLE
Delete https://occusearch.de

### ISSUE THREAD

**Issue by openminded42** [dalf/searx-instances#27]
Instance added by the issue #21

It seems that search engines start to block my instance. Please remove my instance to avoid this.

**Comment by return42** [comment]
> It seems that search engines start to block my instance.

really? .. did you installed filtron?

**Comment by openminded42** [comment]
Yes, I use filtron with a very aggressive tuning I think. I've added my Instance 10 days ago and problems started about 5 days days ago. Often there are NO results. Very often, several search engines fail. However, there are no warnings about this. When I hand DuckDuckGo active, I regularly hand a timeout error. But now, there are no errors. Just missing results. Any other explanation for this behavior?

My filtron config:
```
[{
   "name":"search request",
   "filters":[
      "Param:q",
      "Path=^(/|/search)$"
   ],
   "interval":60,
   "limit":120,
   "subrules":[
      {
         "name":"roboagent limit",
         "interval":120,
         "limit":20,
         "filters":[
            "Header:User-Agent=(curl|cURL|Wget|python-requests|Scrapy|FeedFetcher|Go-http-client)"
         ],
         "actions":[
            {
               "name":"block",
               "params":{
                  "message":"Rate limit exceeded"
               }
            }
         ]
      },
      { 
         "name":"botlimit",
         "limit":0,
         "stop":true,
         "filters":[
            "Header:User-Agent=(Googlebot|bingbot|Baiduspider|yacybot|YandexMobileBot|YandexBot|Yahoo! Slurp|MJ12bot|AhrefsBot|archive.org_bot|msnbot|MJ12bot|SeznamBot|linkdexbot|Netvibes|SMTBot|zgrab|James BOT)"
         ],
         "actions":[
            {
               "name":"block",
               "params":{
                  "message":"Rate limit exceeded"
               }
            }
         ]
      },
      { 
         "name":"IP limit",
         "interval":60,
         "limit":20,
         "stop":true,
         "aggregations":[
            "Header:X-Forwarded-For"
         ],
         "actions":[
            {
               "name":"block",
               "params":{
                  "message":"Rate limit exceeded"
               }
            }
         ]
      },
      { 
         "name":"rss/json limit",
         "interval":300,
         "limit":150,
         "stop":true,
         "filters":[
            "Param:format=(csv|json|rss)"
         ],
         "actions":[
            {
               "name":"block",
               "params":{
                  "message":"Rate limit exceeded"
               }
            }
         ]
      },
      {
         "name":"useragent limit",
         "interval":60,
         "limit":30,
         "aggregations":[
            "Header:User-Agent"
         ],
         "actions":[
            {
               "name":"block",
               "params":{
                  "message":"Rate limit exceeded"
               }
            }
         ]
      }
   ]
}]
```

**Comment by unixfox** [comment]
Sorry for being offtopic but it's pretty much too late, your instance is now in the database of bots and removing it from searx.space won't help.
You may try this improved version of filtron rules: https://github.com/searx/searx-docker/blob/master/rules.json

**Comment by openminded42** [comment]
> Sorry for being offtopic but it's pretty much too late, your instance is now in the database of bots and removing it from searx.space won't help.
> You may try this improved version of filtron rules: https://github.com/searx/searx-docker/blob/master/rules.json and see if this help to combat against bots.

Thank you for that suggestion. I was not aware of the fact that bots are actually such a big problem for searx instances after publishing it on searx.space :/ Hope that helps. Then there is no need to delete my instance.

**Comment by return42** [comment]
> Often there are NO results. Very often, several search engines fail. However, there are no warnings about this. When I hand DuckDuckGo active, I regularly hand a timeout error. But now, there are no errors. Just missing results. Any other explanation for this behavior?

OK this is not filtron and not searx-stat. The reasons can be manifold.  May you are blocked by some search engines due to bots overcome your filtron.  May you have changed or have to change timeouts in the settings.yml ...

If your searx instance is now blocked by some search engines you have to wait they unblock you.

I recommend to start with a default searx installation and a good balanced filtron setup.  The one @unixfox linked I guess is "balanced" another option is to use my setup which works for my since months. https://github.com/return42/searx/blob/filtron/utils/templates/etc/filtron/rules.json (sorry I have not yet time to check yours).  BTW PR https://github.com/asciimoo/searx/pull/1803 improves installation methods if you are interested in read https://return42.github.io/searx/admin/installation.html

If you want to discuss your problems, please open an issue at the searx project  / thanks!

**Comment by dalf** [comment]
> Then there is no need to delete my instance.

I close the issue, feel free to reopen.

**Comment by openminded42** [comment]
Hi,
i further tried to optimize filtron without any success :( There are roughtly 2 Requests per Minute. Es that seems to be to much?! If publish my new instance on occusearch.net. This works now. Now, this instance is open but should only become pupular by my Family, Friends, Friends-of-Friends (month-to-month). Please remove https://occusearch.de from the List (it is offline) and do NOT add my new Instance! Thank you for this project and your support in particular.

best regards,
Markus
