### ISSUE TITLE
Add https://searx.dev

### ISSUE THREAD

**Issue by evanmn** [dalf/searx-instances#28]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

I have not modified any public facing code, and do not log anything. I use a local proxy to allow sending requests from multiple IP ranges. I also use traefik so I do not expose everything on different ports. Does all config of this need to be made public even if no changes were made to Searx itself?

**Comment by dalf** [comment]
> Does all config of this need to be made public even if no changes were made to Searx itself?

Nope, that's all good.
