### ISSUE TITLE
Add https://searx.darklun.ch

### ISSUE THREAD

**Issue by darklunch** [dalf/searx-instances#30]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by darklunch** [comment]
updated dns and enabled ipv6

**Comment by dalf** [comment]
Thank you.

FYI, it seems the HTTP server doesn't listen on the IPv6 address.

**Comment by darklunch** [comment]
Should be working on IPv6 now. Thanks for letting me know!
