### ISSUE TITLE
Add https://searx.pw

### ISSUE THREAD

**Issue by morganlaneap** [dalf/searx-instances#34]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

I have just launched this deployment of Searx-Docker. Let me know if anything needs changing/configuring. I've not modified anything, just deployed straight from the image. Thanks.

**Comment by dalf** [comment]
The https://searx.pw shows the version 0.15.0, but the current version is 0.16.0
If you are using [searx-docker](https://github.com/searx/searx-docker), you should :
```sh
docker-compose pull
./stop.sh
```

**Comment by morganlaneap** [comment]
Will get this updated
