### ISSUE TITLE
Delete searx.dev

### ISSUE THREAD

**Issue by evanmn** [dalf/searx-instances#37]
Instance added by the issue #28 

The bots are more than I had assumed, and are slowing down my instance for personal use. I had to first implement a captcha for some requests on my proxy, and am now on a cloudflare load balancer w/ their WAF. That completely defeats the purpose of Searx of something that can be private as there is no e2e and cloudflare captures 0.5% of all packets along with analytics. I plan to password protect my instance within the month for my own usage and take a white-list approach. I understand that I am already on bot lists, but with a white-list approach that will not be an issue.

**Comment by unixfox** [comment]
Do you use the filtron rules from searx-docker?

**Comment by evanmn** [comment]
I used to use those rules, but now I have made them more strict.

**Comment by unixfox** [comment]
I'm currently using them and I don't have that much issue with bots. In fact it's way better with those than the default rules of filtron given on searx's wiki.
