### ISSUE TITLE
Add searx.privatenet.cf

### ISSUE THREAD

**Issue by djt3** [dalf/searx-instances#39]
* [X] It is my instance.
* [X] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Deployed on a home connection in the UK with a Let's Encrypt cert. Everything is setup as default in the install guide with nginx. Just let me know if anything needs changing.

**Comment by unixfox** [comment]
Do you have a good connection at home? You will probably get a lot of visitors so be prepared to have a good upload bandwidth.

**Comment by djt3** [comment]
The upload speed should be fine but im thinking of upgrading to a remote host in the near future anyway.

**Comment by djt3** [comment]
That's fine, im routing the searches through a proxy so its not on the home ip.

**Comment by dalf** [comment]
Just in case, about filtron, there is a release with compiled binaries: https://github.com/asciimoo/filtron/releases
