### ISSUE TITLE
Add https://searx.lambda.li

### ISSUE THREAD

**Issue by gufertum** [dalf/searx-instances#5]
Thanks

**Comment by Pofilo** [comment]
Hello @gufertum,
I can't access the page "https://searx.lambda.li/", is it normal ?
Thanks.

**Comment by unixfox** [comment]
Me too, HTTP2 error

**Comment by gufertum** [comment]
Sorry, DNS is still fresh... Please retry tomorrow again...

**Comment by unixfox** [comment]
DNS doesn't take that much time to refresh.

**Comment by gufertum** [comment]
Sorry again... i also had a country filter in place.. hope it's working now. I also installed it natively now - is more responsive than using docker...
Thanks for your patience.

**Comment by unixfox** [comment]
I'm using docker it's as fast as I can get natively.
Anyway the instance is working on my part.
