### ISSUE TITLE
https://searx.handskemager.xyz/

### ISSUE THREAD

**Issue by jesperbakhandskemager** [dalf/searx-instances#50]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by dalf** [comment]
I have a SSL_ERROR_BAD_CERT_DOMAIN error.

I guess #51 is the same instance ?

**Comment by unixfox** [comment]
I have the same TLS error but the onion instance is working fine.

**Comment by jesperbakhandskemager** [comment]
Yeah, i know, i will try and get it fixed tonight, but certbot dosen't wan't to certify it

**Comment by jesperbakhandskemager** [comment]
> I have a SSL_ERROR_BAD_CERT_DOMAIN error.
> 
> I guess #51 is the same instance ?

It is

**Comment by dalf** [comment]
Note: your server has an IPv6 address but the HTTP server doesn't listen on it.
