### ISSUE TITLE
Edit https://darmarit.cloud/searx

### ISSUE THREAD

**Issue by return42** [dalf/searx-instances#58]
I can't refer an issue for https://darmarit.cloud/searx since the instance has been added before [searx-instances](https://github.com/dalf/searx-instances) saw the light of day.

Changes:

- https://darmarit.cloud/searx has been moved to https://darmarit.org/searx
- for a short time https://darmarit.cloud/searx redirects to https://darmarit.org/searx

**Comment by unixfox** [comment]
You don't have write access to the repository?

**Comment by dalf** [comment]
@return42 you can call 
```
python -m searxinstances.update --github-issues 58
```

if there was no issue 58:
```
python -m searxinstances.update --edit https://darmarit.cloud/searx
```

You have write access to the repository. If it doesn't work tell me.

**Comment by return42** [comment]
Hm .. 

````python
$ python -m searxinstances.update --github-issues 58
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/800GBPCIex4/share/searx-instances/searxinstances/update.py", line 21
    def __init__(self, request_id: str, request_url: str, user: str, url: str, message: str):
````

OK .. it is python3 .. next try:

````python
$ python3 -m searxinstances.update --github-issues 58
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/800GBPCIex4/share/searx-instances/searxinstances/update.py", line 6, in <module>
    import git
ModuleNotFoundError: No module named 'git'
````

OK I have to install some packages .. next try:

````bash
$ make install
python -m pip install --upgrade pip
DEPRECATION: Python 2.7 reached the ...
````

OK, I have to RTFM ...

````
usage: update.py [-h]
                 [--github-issues [GITHUB_ISSUE_LIST [GITHUB_ISSUE_LIST ...]]]
                 [--add [ADD_INSTANCES [ADD_INSTANCES ...]]]
                 [--delete [DELETE_INSTANCES [DELETE_INSTANCES ...]]]
                 [--edit [EDIT_INSTANCES [EDIT_INSTANCES ...]]]
````

````bash
$ ls
LICENSE  Makefile  README.md  requirements-dev.txt  requirements.txt  requirements-update.txt  searxinstances  setup.py  tests
````

Hm .. where is that `update.py`?

@dalf what do you think, where is my fail .. how did you install / run the update script?

**Comment by unixfox** [comment]
Or you just have to:
```bash
git clone git@github.com:dalf/searx-instances.git
cd searx-instances
pip3 install -r requirements.txt
python -m searxinstances.update --edit https://darmarit.cloud/searx
```

**Comment by return42** [comment]
> Or you just have to:

@dalf even this hangs in my emacs server mode :) ... my fail .. to keep things simple I edit searxinstances/instances.yml in my editor and wrote the commit message from the template.

For me this was the more simple solution, I hope I have made no fail.

Thanks to all for your help!

**Comment by dalf** [comment]
Ah.. it lacks some documentation.

You can set the [EDITOR environment variable](https://github.com/dalf/searx-instances/blob/master/searxinstances/utils/editor.py#L78) to whatever you want (instead of [emacs](https://github.com/dalf/searx-instances/blob/master/searxinstances/utils/editor.py#L31)).

But it is only an helper that make sure:
* the commit message is noramlized
* there is no yaml syntax error
* the instance is in alphabetical order

If you edit the file directly, you can run
```
make check
```
to validate the yaml file.
