### ISSUE TITLE
https://searx.sunless.cloud/

### ISSUE THREAD

**Issue by random-letter** [dalf/searx-instances#6]

**Comment by dalf** [comment]
@random-letter just in case, nothing mandatory:
```
<meta http-equiv="Content-Security-Policy" default-src 'self'; img-src 'self'>
```
must probably should be
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self'">
```

For information, the Content-Security-Policy value in searx-docker: https://github.com/searx/searx-docker/blob/f2e6ca4a610d9ccf66d4e16ac210bdb1bd4fff0c/Caddyfile#L32
