### ISSUE TITLE
Add https://searx.olymp.to

### ISSUE THREAD

**Issue by RoterSalamander** [dalf/searx-instances#60]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by onmyouji** [comment]
This instance seems to be down

**Comment by unixfox** [comment]
> This instance seems to be down

That's fine, searx.space filtered it from the working instances list. If the instance goes back up one day then searx.space will add it back to the working instances list.

**Comment by RoterSalamander** [comment]
Instance is back up and running again :)
