### ISSUE TITLE
Add https://searx.queendairy.xyz

### ISSUE THREAD

**Issue by QDesjardin** [dalf/searx-instances#68]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by dalf** [comment]
It seems you have neither [filtron](https://github.com/asciimoo/filtron) nor [antibot-proxy](https://github.com/unixfox/antibot-proxy).

One of them is highly recommend to protect your instance from the bot.

**Comment by return42** [comment]
I recommend to read our new [installation manual](https://asciimoo.github.io/searx/admin/installation.html)

**Comment by QDesjardin** [comment]
Yes, I tried out the updated installation manual and ran the scripts, but I wasn't able to get nginx working with the lines provided for filtron and morty - I had to use [Luke Smith's video](https://www.youtube.com/watch?v=oufXi3e-VuA) to get nginx and my instance up and running.

For reference, this is what my nginx file for searx looks like:

`server {
  server_name searx.queendairy.xyz;
  root /usr/local/searx/searx;

  location /searx {
    proxy_pass         http://127.0.0.1:4004/;

    proxy_set_header   Host             $http_host;
    proxy_set_header   Connection       $http_connection;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Scheme         $scheme;
    proxy_set_header   X-Script-Name    /searx;
  }

  location /searx/static {
    alias /usr/local/searx/searx-src/searx/static;
  }

  location /morty {
    proxy_pass         http://127.0.0.1:3000/;

    proxy_set_header   Host             $http_host;
    proxy_set_header   Connection       $http_connection;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Scheme         $scheme;
  }

  location / {
    include uwsgi_params;
    uwsgi_pass unix:/run/uwsgi/app/searx/socket;
  }

    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/searx.queendairy.xyz/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/searx.queendairy.xyz/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = searx.queendairy.xyz) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  listen [::]:80;
  server_name searx.queendairy.xyz;
    return 404; # managed by Certbot


}`

**Comment by return42** [comment]
> I had to use Luke Smith's video 

I don't know why, but the video uses a (very) old installation man

> Yes, I tried out the updated installation manual and ran the scripts, but I wasn't able to get nginx working with the lines provided for filtron and morty 

If you think you have found a bug, please add an issue at https://github.com/asciimoo/searx/issues

**Comment by QDesjardin** [comment]
Ok, now it's running SearX properly using Filtron, I simply had to change it to this:

````
  location / {
    proxy_pass         http://127.0.0.1:4004/;

    proxy_set_header   Host             $http_host;
    proxy_set_header   Connection       $http_connection;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Scheme         $scheme;
    proxy_set_header   X-Script-Name    /searx;
  }

  location /static {
    alias /usr/local/searx/searx-src/searx/static;
  }

  location /morty {
    proxy_pass         http://127.0.0.1:3000/;

    proxy_set_header   Host             $http_host;
    proxy_set_header   Connection       $http_connection;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Scheme         $scheme;
  }
````

**Comment by return42** [comment]
>  I simply had to change it to this:

Where does it come from, what was the origin, is it a bug in our docs? >

To show what you have changed, a diff is more helpful.

**Comment by dalf** [comment]
> Ok, now it's running SearX properly using Filtron

One more things, I strongly recommend you to disable the JSON/RSS/CSV outputs: 
```json
            {
                "name": "rss/json limit",
                "interval": 3600,
                "limit": 0,
                "stop": true,
                "filters": ["Param:format=(csv|json|rss)"],
                "aggregations": ["Header:X-Forwarded-For"],
                "actions": [
                    {"name": "block",
		     "params": {"message": "Rate limit exceeded, try again later."}}
                ]
            },
```
(see https://github.com/searx/searx-docker/blob/bdf5619765ac9457eb0bb4107dba2db10eddd724/rules.json#L103-L114 and )

* If you want, you can improve your nginx security configuration: https://github.com/searx/searx-docker/blob/bdf5619765ac9457eb0bb4107dba2db10eddd724/rules.json#L103-L114

After that, all good.

**Comment by QDesjardin** [comment]
> Where does it come from, what was the origin, is it a bug in our docs? >
> 
> To show what you have changed, a diff is more helpful.

The video I followed came only a month ago, which I find bizarre to refer to it as a "very old installation." Going by the video's recent comments, the instructions were updated, apparently in realisation that the SearX instances were vulnerable to botting. People mentioned that the new instructions were rather abstruse, because:

- the scripts' installations overlapped one another (i.e. installing nginx three times in a row if you answered yes to all questions), 
- issues with dependencies when going by the scripts (no OS-specific stuff is ever mentioned on [this page](https://asciimoo.github.io/searx/admin/installation.html), it's probably assumed the user is running Debian; Arch, Ubuntu and RHEL-based distros use different package names), and
- attempting to use the filtron + morty setup under nginx, [exactly as written](https://asciimoo.github.io/searx/admin/installation-nginx.html#installation-nginx), leads to nginx being unable to start. Also, it is likely presumed that the user is going to run SearX as its own webpage, rather than a subdomain:

````
(no server { } section is ever mentioned)
location /searx {
  ...
}

location /searx/static {
  /usr/local/searx/searx-src/searx/static;
}

location /morty {
  ...
}
````

I had to change it to this:

````
server {
  server_name searx.queendairy.xyz;

  location / {
    ...
  }

  location /static {
    alias /usr/local/searx/searx-src/searx/static;
  }

  location /morty {
    ...
  }
}

server {
  listen 80;
  listen [::]:80;
  server_name searx.queendairy.xyz;
}
````

then get it certified under certbot afterwards (necessary for secure webpage), which instructions do not mention.

> (see https://github.com/searx/searx-docker/blob/bdf5619765ac9457eb0bb4107dba2db10eddd724/rules.json#L103-L114 and )
> If you want, you can improve your nginx security configuration: https://github.com/searx/searx-docker/blob/bdf5619765ac9457eb0bb4107dba2db10eddd724/rules.json#L103-L114

Link is the same as first link.

**Comment by return42** [comment]
> The video I followed came only a month ago, which I find bizarre to refer to it as a "very old installation." 

The video is new, but the installation instruction which are shown in the video are _old_ / We have revised the entire [installation manual](https://asciimoo.github.io/searx/admin/installation.html) / compare it with the one shown in the video.  So I guess the video was recorded a few month ago and was uploaded recently.

> the scripts' installations overlapped one another (i.e. installing nginx three times in a row if you answered yes to all questions) -- "Do I install all three scripts???"

The scripts and the installation instructions are new .. we are open for improvements.

>  it's probably assumed the user is running Debian; Arch, Ubuntu and RHEL-based

This is what we _support_ at that time.  The scripts and the documentation are scalable to cover other distributions as well. Contributions are welcome.

> attempting to use the filtron + morty setup under nginx, exactly as written, leads to nginx being unable to start. 

If you found a bug, please add an issue.

> Also, it is likely presumed that the user is going to run SearX as its own webpage, rather than a subdomain (which I use):

Surely, that's true .. The HTTP(s) setup is the logical limit .. we cannot cover all cases. But we can add examples to the documentation. E.g. I really miss documentation about  a [cerbot setup](https://certbot.eff.org/docs/using.html) / every contribution is also welcome here.

> I had to change it to this to get things working properly:

Sounds logical to set the server name  ..

> (no server { } section is ever mentioned)

This really depends on the distribution, we describe this _include_ structure for [debian, archlinux, RHEL](https://asciimoo.github.io/searx/admin/installation-nginx.html#the-nginx-http-server).

Which distro you are using?

**Comment by QDesjardin** [comment]
I'm running latest version Debian on my VPS. The issue with nginx being unable to start from the provided config isn't a bug, but rather a syntax issue -- forgot to put "alias" under the "location /static" part. Sorries if I wasn't clear on that.

One last thing: 

> If you want, you can improve your nginx security configuration: ...

I was wondering what you originally intended to link to here, cause it just links to filtron's rules.json.

**Comment by dalf** [comment]
> I was wondering what you originally intended to link to here, cause it just links to filtron's rules.json.

https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1d&guideline=5.4

**Comment by return42** [comment]
> The issue with nginx being unable to start from the provided config isn't a bug, but rather a syntax issue -- forgot to put "alias" under the "location /static" part. Sorries if I wasn't clear on that.

A syntax issue is a bug, If you found a bug in searx installation procedure, please add an issue to the searx project, don't post it here in the searx-instance project.
