### ISSUE TITLE
Add https://searx.gnu.style

### ISSUE THREAD

**Issue by dasj19** [dalf/searx-instances#69]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

I would like to add my instance https://searx.gnu.style to the list of available searx instances. Thnak you

**Comment by dalf** [comment]
It seems you have neither [filtron](https://github.com/asciimoo/filtron) nor [antibot-proxy](https://github.com/unixfox/antibot-proxy).

One of them is highly recommend to protect your instance from the bot.

**Comment by return42** [comment]
I recommend to read our new [installation manual](https://asciimoo.github.io/searx/admin/installation.html)

**Comment by dasj19** [comment]
Okay, now I packaged filtron for my distro (NixOS): https://github.com/NixOS/nixpkgs/pull/93181
And I am ready for going public with the instance.

**Comment by dalf** [comment]
Done: https://github.com/dalf/searx-instances/commit/c9fcbdd659121b06a873219437364a6bde261a5a
