### ISSUE TITLE
Add https://search.javasight-dev.online

### ISSUE THREAD

**Issue by bbqswan** [dalf/searx-instances#71]
* x It is my instance.
* x I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by dalf** [comment]
It seems [filtron](https://asciimoo.github.io/searx/utils/filtron.sh.html) is not configured.

Please be sure to have configured filtron:
* once your instance is added to searx.space, it will receive requests from different bots which may increase its chance of getting blocked by various search engines.
* removing your instance from searx.space won't stop the bots and thus will most likely not unblock it from the various search engines.

**Comment by bbqswan** [comment]
Sorry, this won't work on my domain and I don't have the search set up anymore.
