### ISSUE TITLE
Add https://searx.drinco.xyz

### ISSUE THREAD

**Issue by drincoxyz** [dalf/searx-instances#72]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by dalf** [comment]
It seems [filtron](https://asciimoo.github.io/searx/utils/filtron.sh.html) is not configured.

Please be sure to have configured filtron:
* once your instance is added to searx.space, it will receive requests from different bots which may increase its chance of getting blocked by various search engines.
* removing your instance from searx.space won't stop the bots and thus will most likely not unblock it from the various search engines.

**Comment by dalf** [comment]
The instance doesn't exist anymore.

Feel free to reopen the issue, if the situation changes.
