### ISSUE TITLE
Add https://searx.vitanetworks.link

### ISSUE THREAD

**Issue by vitaprimo** [dalf/searx-instances#73]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

I only modified the hero images from the `oscar` theme, no code edited. [I made another _vanilla_ set hoping I could offer them to the project with SVGs so they can be reedited](https://github.com/vitaprimo/searx/tree/master/searx/static/logos), I would be honored if you accept them even if you don't use them. 🙇🏼‍♂️

About the instance; filtron+morty are installed: It is behind Cloudflare _and_, queries leave over dynamic and/or tunneled IP addresses, not via the instance's public facing IPv4/6 address.

Thanks.

**Comment by dalf** [comment]
Thank you !

I'm not sure if this is your intent: morty gives access to any URL (usually morty is configured with key, so only the URL referenced by searx can be accessed).

----

May I ask you
* to change https://github.com/vitaprimo/searx/blob/eef893eb7302a66c0590f1582f7c2dfbd3fd921a/Makefile#L5 to your git URL
* to run ```make buildenv```
?

So https://searx.vitanetworks.link/config (the brand.GIT_URL field) displays the right git URL.

----

> I would be honored if you accept them even if you don't use them. 🙇🏼‍♂️

Can you open an issue on here: https://github.com/asciimoo/searx/issues ? But I'm not sure how to add the images you have made (perhaps new a oscar style).
