### ISSUE TITLE
Add serx.ml

### ISSUE THREAD

**Issue by TheAngryPython** [dalf/searx-instances#74]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by dalf** [comment]
It seems [filtron](https://asciimoo.github.io/searx/utils/filtron.sh.html) is not configured.

Please be sure to have configured filtron:
* once your instance is added to searx.space, it will receive requests from different bots which may increase its chance of getting blocked by various search engines.
* removing your instance from searx.space won't stop the bots and thus will most likely not unblock it from the various search engines.

**Comment by unixfox** [comment]
Be aware that when using a freenom domain you don't own the domain: https://www.reddit.com/r/webhosting/comments/82ksmp/freenom_took_my_free_domain_away/

**Comment by dalf** [comment]
I close the request as https is not available.
