### ISSUE TITLE
Add https://searx.sp-codes.de

### ISSUE THREAD

**Issue by samuel-p** [dalf/searx-instances#81]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by dalf** [comment]
It seems neither [filtron](https://github.com/asciimoo/filtron/) nor [antibot-proxy](https://github.com/unixfox/antibot-proxy) are installed.

In the current setup, different bots will abuse your instance until the search engines (google,etc..) ask for a captcha for each request.

If you are using docker, I strongly encourage you to see the default setup : https://github.com/searx/searx-docker especially [rules.json](https://github.com/searx/searx-docker/blob/master/rules.json)

**Comment by samuel-p** [comment]
Yes, I didn't setup filtron, when I created my instance. I added it now with the [rules.json](https://github.com/searx/searx-docker/blob/master/rules.json) you linked. Can you check again, if it is working as expected? Is there anything else I need to do?

**Comment by dalf** [comment]
According to https://cryptcheck.fr/https/searx.sp-codes.de the HTTPS server supports RSA, 3DES and MAC SHA1. There protocols are outdated. You can use https://ssl-config.mozilla.org/ to have configuration example.

But, there is nothing mandatory about that.

**Comment by samuel-p** [comment]
Thanks for adding, I will take a look at that later this evening.

**Comment by samuel-p** [comment]
I have also setup a hidden service for my instance: http://searxbi3f73mmdeb.onion/
Maybe you want to add it to your list too?

**Comment by unixfox** [comment]
@samuel-p Done in https://github.com/searx/searx-instances/commit/dec95c99ffdffbb180f8d5c731fc633db5758d63

**Comment by samuel-p** [comment]
I noticed that my instance is listed on the list of offline instances and I'm not sure why it's there. It's possible, that it was offline one time it was checked, but that was some days ago. Are the offline instances checked again or need they be moved to the online instances manually?

**Comment by dalf** [comment]
>  Are the offline instances checked again or need they be moved to the online instances manually?

Online and offline instances are checked every 3 hours. If an offline instance is seen as online again, the status is updated.

The searx.sp-codes.de is responding on the IPv4 but not on the IPv6. I need to investigate, but I think searx-stats2 try only the IPv6 (browsers usually fall back on the IPv4).

**Comment by samuel-p** [comment]
Thanks for your quick feedback. Actually ipv6 should also be supported, but apparently there was a bug in my config. I fixed it now and ipv6 should work again, so the instance should be listed under online soon.
